### ISSUE TITLE
Transformer error .when I was trying to save model I got this error.

### ISSUE THREAD

**Issue by Somabhadra** [keras-team/keras-io#405]
Code
from keras.models import load_model 
model.save("transformer1.h5") 

ERROR
NotImplementedError                       Traceback (most recent call last)
<ipython-input-16-2a7c7e5b2ce5> in <module>
      1 from keras.models import load_model
----> 2 model.save("transformer1.h5")

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options, save_traces)
   1999     """
   2000     # pylint: enable=line-too-long
-> 2001     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
   2002                     signatures, options, save_traces)
   2003 

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options, save_traces)
    151           'to the Tensorflow SavedModel format (by setting save_format="tf") '
    152           'or using `save_weights`.')
--> 153     hdf5_format.save_model_to_hdf5(
    154         model, filepath, overwrite, include_optimizer)
    155   else:

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    113 
    114   try:
--> 115     model_metadata = saving_utils.model_metadata(model, include_optimizer)
    116     for k, v in model_metadata.items():
    117       if isinstance(v, (dict, list, tuple)):

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\saving_utils.py in model_metadata(model, include_optimizer, require_config)
    156   except NotImplementedError as e:
    157     if require_config:
--> 158       raise e
    159 
    160   metadata = dict(

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\saving\saving_utils.py in model_metadata(model, include_optimizer, require_config)
    153   model_config = {'class_name': model.__class__.__name__}
    154   try:
--> 155     model_config['config'] = model.get_config()
    156   except NotImplementedError as e:
    157     if require_config:

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\functional.py in get_config(self)
    648 
    649   def get_config(self):
--> 650     return copy.deepcopy(get_network_config(self))
    651 
    652   @classmethod

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\functional.py in get_network_config(network, serialize_layer_fn)
   1347         filtered_inbound_nodes.append(node_data)
   1348 
-> 1349     layer_config = serialize_layer_fn(layer)
   1350     layer_config['name'] = layer.name
   1351     layer_config['inbound_nodes'] = filtered_inbound_nodes

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\utils\generic_utils.py in serialize_keras_object(instance)
    248         return serialize_keras_class_and_config(
    249             name, {_LAYER_UNDEFINED_CONFIG_KEY: True})
--> 250       raise e
    251     serialization_config = {}
    252     for key, item in config.items():

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\utils\generic_utils.py in serialize_keras_object(instance)
    243     name = get_registered_name(instance.__class__)
    244     try:
--> 245       config = instance.get_config()
    246     except NotImplementedError as e:
    247       if _SKIP_FAILED_SERIALIZATION:

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer.py in get_config(self)
    697     # or that `get_config` has been overridden:
    698     if len(extra_args) > 1 and hasattr(self.get_config, '_is_default'):
--> 699       raise NotImplementedError('Layer %s has arguments in `__init__` and '
    700                                 'therefore must override `get_config`.' %
    701                                 self.__class__.__name__)

NotImplementedError: Layer TokenAndPositionEmbedding has arguments in `__init__` and therefore must override `get_config`.

**Comment by Somabhadra** [comment]
now its working.i fixed it.override with get_config.

**Comment by mo-alaa** [comment]
@Somabhadra How did you override it ?  in my case, I find the `_get_config_` is already overriden ! and I still get the same error!
